/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { MarkupItem, IssueItem, DrawingSheetInfo, DiffReport } from '../types';

export function downloadFile(content: string | Blob, filename: string, mimeType = 'text/plain') {
  const blob = content instanceof Blob ? content : new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportMeasurementsCsv(markups: MarkupItem[]): string {
  const measurements = markups.filter(m => m.measurementValue !== undefined || m.type === 'count');
  const headers = ['ID', 'Page', 'Discipline', 'Type', 'Value', 'Unit', 'Label/Text', 'Author', 'Date'];
  const rows = measurements.map(m => [
    `"${m.id}"`,
    `"${m.pageIndex + 1}"`,
    `"${m.discipline}"`,
    `"${m.type.toUpperCase()}"`,
    `"${m.measurementValue ?? 1}"`,
    `"${m.measurementUnit || 'EA'}"`,
    `"${(m.text || m.formattedMeasurement || m.countCategory || '').replace(/"/g, '""')}"`,
    `"${m.author}"`,
    `"${m.createdAt.slice(0, 10)}"`,
  ]);

  return [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
}

export function exportIssuesCsv(issues: IssueItem[]): string {
  const headers = ['Issue ID', 'Title', 'Description', 'Page', 'Discipline', 'Priority', 'Status', 'Assignee', 'Due Date'];
  const rows = issues.map(i => [
    `"${i.id}"`,
    `"${i.title.replace(/"/g, '""')}"`,
    `"${i.description.replace(/"/g, '""')}"`,
    `"${i.pageIndex + 1}"`,
    `"${i.discipline}"`,
    `"${i.priority.toUpperCase()}"`,
    `"${i.status.toUpperCase()}"`,
    `"${i.assignee}"`,
    `"${i.dueDate}"`,
  ]);

  return [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
}

export function generatePrintableReportHtml(
  projectInfo: Partial<DrawingSheetInfo>,
  markups: MarkupItem[],
  issues: IssueItem[],
  diffReport?: DiffReport
): string {
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>BIM Studio - AEC Drawing Review Report</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; color: #1e293b; padding: 40px; margin: 0; background: #ffffff; }
    h1 { font-size: 24px; margin-bottom: 4px; color: #0f172a; border-bottom: 2px solid #0f172a; padding-bottom: 8px; }
    h2 { font-size: 16px; margin-top: 28px; margin-bottom: 12px; color: #334155; text-transform: uppercase; letter-spacing: 0.05em; }
    .meta-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 16px; margin-bottom: 24px; display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; font-size: 13px; }
    .meta-item strong { display: block; font-size: 11px; color: #64748b; text-transform: uppercase; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; font-size: 12px; }
    th { background: #f1f5f9; text-align: left; padding: 8px 10px; border: 1px solid #cbd5e1; font-weight: 600; color: #475569; }
    td { padding: 8px 10px; border: 1px solid #e2e8f0; }
    tr:nth-child(even) { background: #fafafa; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 10px; font-weight: 600; }
    .badge-open { background: #fee2e2; color: #991b1b; }
    .badge-resolved { background: #dcfce7; color: #166534; }
    .badge-review { background: #fef9c3; color: #854d0e; }
    .diff-box { background: #f0fdf4; border: 1px solid #bbf7d0; padding: 14px; border-radius: 6px; font-size: 13px; }
    .disclaimer { margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 12px; font-size: 11px; color: #64748b; font-style: italic; }
  </style>
</head>
<body>
  <h1>AEC DRAWING REVIEW & BIM ISSUE REPORT</h1>
  <div class="meta-box">
    <div class="meta-item"><strong>Project Name</strong> ${projectInfo.projectName || 'Metropolitan Medical Center - Phase 2'}</div>
    <div class="meta-item"><strong>Drawing Number</strong> ${projectInfo.sheetNumber || 'A-101'}</div>
    <div class="meta-item"><strong>Current Revision</strong> ${projectInfo.revision || 'Rev 03'}</div>
    <div class="meta-item"><strong>Discipline</strong> ${projectInfo.discipline || 'Architectural'}</div>
    <div class="meta-item"><strong>Report Date</strong> ${dateStr}</div>
    <div class="meta-item"><strong>Generated By</strong> BIM Studio AEC Platform</div>
  </div>

  <h2>1. Drawing Review Issues & Action Items (${issues.length})</h2>
  <table>
    <thead>
      <tr>
        <th>Issue ID</th>
        <th>Title</th>
        <th>Page</th>
        <th>Discipline</th>
        <th>Priority</th>
        <th>Status</th>
        <th>Assignee</th>
        <th>Due Date</th>
      </tr>
    </thead>
    <tbody>
      ${issues.map(i => `
        <tr>
          <td><strong>${i.id}</strong></td>
          <td>${i.title}</td>
          <td>Pg ${i.pageIndex + 1}</td>
          <td>${i.discipline}</td>
          <td>${i.priority.toUpperCase()}</td>
          <td><span class="badge ${i.status === 'resolved' ? 'badge-resolved' : i.status === 'in_review' ? 'badge-review' : 'badge-open'}">${i.status.toUpperCase()}</span></td>
          <td>${i.assignee}</td>
          <td>${i.dueDate}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  <h2>2. Drawing Markups & Measurement Takeoffs (${markups.length})</h2>
  <table>
    <thead>
      <tr>
        <th>Markup ID</th>
        <th>Page</th>
        <th>Type</th>
        <th>Discipline</th>
        <th>Measured Value / Content</th>
        <th>Category</th>
        <th>Author</th>
      </tr>
    </thead>
    <tbody>
      ${markups.map(m => `
        <tr>
          <td><strong>${m.id}</strong></td>
          <td>Pg ${m.pageIndex + 1}</td>
          <td>${m.type.toUpperCase()}</td>
          <td>${m.discipline}</td>
          <td>${m.formattedMeasurement || m.text || (m.measurementValue !== undefined ? `${m.measurementValue} ${m.measurementUnit || ''}` : '-')}</td>
          <td>${m.colorCategory.toUpperCase()}</td>
          <td>${m.author}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  ${diffReport ? `
  <h2>3. Revision Comparison & Change Detection</h2>
  <div class="diff-box">
    <p><strong>Summary:</strong> ${diffReport.summary}</p>
    <p><strong>Key Metrics:</strong> Added Elements: ${diffReport.addedCount} | Removed Elements: ${diffReport.removedCount} | Modified Zones: ${diffReport.modifiedCount}</p>
  </div>
  <table>
    <thead>
      <tr>
        <th>Change ID</th>
        <th>Type</th>
        <th>Location</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      ${diffReport.changes.map(c => `
        <tr>
          <td><strong>${c.id}</strong></td>
          <td style="color:${c.type === 'added' ? '#16a34a' : c.type === 'removed' ? '#dc2626' : '#d97706'}"><strong>${c.type.toUpperCase()}</strong></td>
          <td>${c.location}</td>
          <td>${c.description}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>
  ` : ''}

  <div class="disclaimer">
    IMPORTANT DISCLAIMER: BIM Studio measurements and AI analysis are document-review aids and do not replace professional architectural or structural engineering judgment. Verify all critical dimensions on site before fabrication or construction.
  </div>
</body>
</html>`;
}

export function exportTakeoffScheduleCsv(
  categories: Array<{ id: string; name: string; count: number; scheduleCode?: string; unitCost?: number; discipline?: string }>
): string {
  const headers = ['Schedule Code', 'Item Name', 'Discipline', 'Quantity (Count)', 'Unit Cost ($)', 'Subtotal ($)'];
  const rows = categories.map((c) => {
    const qty = c.count || 0;
    const unitCost = c.unitCost !== undefined ? c.unitCost : 0;
    const total = qty * unitCost;
    return [
      `"${(c.scheduleCode || c.id.toUpperCase()).replace(/"/g, '""')}"`,
      `"${c.name.replace(/"/g, '""')}"`,
      `"${(c.discipline || 'Architectural').replace(/"/g, '""')}"`,
      qty,
      unitCost.toFixed(2),
      total.toFixed(2),
    ];
  });

  const totalCost = categories.reduce((sum, c) => sum + (c.count || 0) * (c.unitCost || 0), 0);
  const totalQty = categories.reduce((sum, c) => sum + (c.count || 0), 0);
  const summaryRow = ['"TOTAL"', '"All Scheduled Items"', '""', totalQty, '""', totalCost.toFixed(2)];

  return [headers.join(','), ...rows.map((r) => r.join(',')), summaryRow.join(',')].join('\n');
}

export const generateReviewSummaryHtml = generatePrintableReportHtml;
